twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    date:
        timezone: 'Europe/Paris'
    number_format:  
      decimals: 2
      decimal_point: ','
      thousands_separator: ' ' 
