parameters:
    app.dir.private_files: '%kernel.project_dir%/var' 
      # Un répertoire générique pour tous les fichiers privé qui doivent être stocké sur le site
    private.download.dirname: '%app.dir.private_files%\dirname' 
      # Le sous-répertoire où stocké un  type de fichier en particulier (Par exemple 'order' pour stocker des commandes client)
    locale: 'fr'

services:
    _defaults:
        autowire: true       
        autoconfigure: true  
      
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
